### ISSUE TITLE
Feature Request :: View book details within Wishlist

### ISSUE THREAD

**Issue by Shacamus** [shockbytes/Dante#108]
Hello

Would it be tricky to allow book details to be seen within Wishlist? 
I think this would be really helpful. 

Ps :I'll try to develop this on my behalf - if working, will create a PR.

Thanks.

**Comment by shockbytes** [comment]
Hey @Shacamus!

No worries, I'm currently working on it and this will also be enabled!

**Comment by Shacamus** [comment]
Found out how to activate it.  😁

**Comment by shockbytes** [comment]
I close this issue since it's now officially supported
