### ISSUE TITLE
Contribution help: Getting oauth_client_id.xml

### ISSUE THREAD

**Issue by lockieRichter** [shockbytes/Dante#139]
Hi,

I am trying to get the source code setup and running locally. I have followed the instructions for getting started, but can't seem to be able to get the oauth_client_id.xml from the Google Cloud Console. I think I am able to get something that might be the correct thing but in JSON form, but I am not 100%.

Are you able to provide some more detailed instructions on how to get the oauth_client_id.xml from Google Cloud Console?

Love the app, looking forward to being able to contribute.

Thanks,
Lockie

**Comment by lockieRichter** [comment]
@shockbytes

**Comment by shockbytes** [comment]
Hello @lockieRichter. Thank you for reaching out. I'm sorry for the delay, I'm kinda busy with other stuff too. If you want to contribute, please reach out to `shockbytesstudio@gmail.com` so we can further discuss this topic.

Once again, sorry for the late reply.
