### ISSUE TITLE
Feature Request: Monthly & Yearly Reading goals

### ISSUE THREAD

**Issue by margaretski** [shockbytes/Dante#53]
I'd love to see a way to enter our goals in either pages or books or both for each month and year. Plus have progress stats and other useful info related to that.

**Comment by shockbytes** [comment]
Hey @margaretski! 

I like your ideas. Can you explain them in more detail so that I can better think of how I could bake this feature into the app.

**Comment by anilozdemir** [comment]
Progress stats would be very helpful indeed! We are entering how many pages we read for each book item, the app can store the datetime of the entry, and show some graphs such as (i) total read over time and (ii) total read per book. Even if the app does not show a graph at the first instance, it would be cool if it stores the data and allows to download as CSV.

**Comment by shockbytes** [comment]
After another round of evaluating the feature, it seems quite promising that it will make it into the next release `v3.14`.

Although, however, I depict it a bit differently from your suggestions. I see the feature as a reading graph per book, with the possibility to derive some useful information like @margaretski mentioned pages read for each month or year.

I am kind of reluctant to add the "Goals" feature as I try to not overload the app with different sets of features. It also requires more programming time (which is scarce at the moment).
However, this first step would allow us to add the goals feature later on anyways.

**Comment by shockbytes** [comment]
UPDATE: The pages read per day are now stored and will be shipped in `v3.14`. Graphs which render the pages and books read over time (with the possibility to enter goals) will be shipped in the upcomming version `3.15` (currently in development).

Since these changes will make it into the app in the near future, I'm gonna close this issue now.
