### ISSUE TITLE
Start reading date.

### ISSUE THREAD

**Issue by margaretski** [shockbytes/Dante#54]
Is there a way to enter the "start reading date". I'm adding all of my books from 2019, and can't seem to find this feature.

**Comment by shockbytes** [comment]
Hey @margaretski ! You can click on icons at the bottom of the details screen. The one thing is that you have to move them through all 3 states manually, otherwise not all buttons will appear.

**Comment by shockbytes** [comment]
This issue has been ship already. I close this issue.
