### ISSUE TITLE
Barcode scanner doesn't work

### ISSUE THREAD

**Issue by codebude** [shockbytes/Dante#59]
When using the scanner function the camera image is shown, but it doesn't recognize any Barcodes nor it shows any overlay or button. Just a camera preview.

**Comment by Shacamus** [comment]
I'd say this ticket can be closed.
(1) it's a very old ticket
(2) Dante migrated to another camera 
(3) no user complains since that date. 

@shockbytes, any thoughts?

**Comment by codebude** [comment]
Thanks for remembering me. I retried to scan some barcodes and it is working fine now. So this ticket can be closed...

**Comment by shockbytes** [comment]
Thanks for taking care of that @codebude @Shacamus!
