### ISSUE TITLE
Feature request: tags

### ISSUE THREAD

**Issue by airon90** [shockbytes/Dante#61]
I'd like to mark some books so that I can then filter out, e.g. I'd like to mark some books I have read and some other I want to read as "I want to buy it" or "Thriller book" so that I can show my friend which thriller books I read or I want to read or I can easily find out which book I want to buy without searching them manually

**Comment by shockbytes** [comment]
Hey @airon90!

Tags (or `labels` as they will be called) are near to completion and will be shipped within the next month (hopefully 🤞 )

**Comment by shockbytes** [comment]
This issue has been shipped. I close the issue.
