### ISSUE TITLE
Restoring Backup not working

### ISSUE THREAD

**Issue by theTPH** [shockbytes/Dante#80]
Hi, i  got a problem with the google drive backup.
When I try to load one of my 2 backups i get a java.lang.NumberFormatException.
I attached the error message as screenshot.
Would be cool if you could fix this.

![Screenshot_20200224-190555_Dante](https://user-images.githubusercontent.com/33541639/75179002-6eaff880-5739-11ea-91c5-b91b3bb61dc8.jpg)
![Screenshot_20200224-190520_Dante](https://user-images.githubusercontent.com/33541639/75179005-6f488f00-5739-11ea-99f5-4c6dc77d8bea.jpg)

**Comment by shockbytes** [comment]
This should be fixed with the upcoming release `3.16`.
