### ISSUE TITLE
Backing up freezes the app

### ISSUE THREAD

**Issue by airon90** [shockbytes/Dante#94]
I have to back up my data because I bought a new smartphone. When I try to backup either in the standard way or by creating a CSV freezes the app.

Meanwhile you fix this problem, how can I back up and restore my data by using ```adb```?

**Comment by shockbytes** [comment]
Hi @airon90!

I didn't have much time to address the bug. However, I just opened a PR #102 exactly addressing the bug. A bug fix should be available in the coming week.

**Comment by shockbytes** [comment]
Closing this PR because it will be fixed in upcoming release `v3.16`
